# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  CppEngine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := CppEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CppEngine:
ifneq (,$(CppEngine_config))
	@echo "==== Building CppEngine ($(CppEngine_config)) ===="
	@${MAKE} --no-print-directory -C . -f CppEngine.make config=$(CppEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f CppEngine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CppEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"